import type { Metadata } from 'next';
import { Geist, Geist_Mono, Bitcount_Grid_Double } from 'next/font/google';
import './globals.css';
import AppHeader from '@/features/navbar/components/app-header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const bitcountGridDouble = Bitcount_Grid_Double({
  variable: '--font-bitcount-grid-double',
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bitcountGridDouble.variable} antialiased h-dvh`}
      >
        <main className='flex min-h-screen flex-col items-center'>
          <AppHeader />
          {children}
        </main>
      </body>
    </html>
  );
}
